// Use CommonJS require for compatibility
const { PrismaClient } = require("../generated/prisma");
const prisma = new PrismaClient();

const pricingOptions = [
  { description: "8x10 (Standard)", amount: 12.0 },
  { description: "11x14 (Large)", amount: 14.0 },
];

// Auto-generated from /public/images
const products = [
  {
    title: "Painter house with tree - 01",
    description: "Painter house with tree - 01",
    category: "CONTEMPORARY",
    imageURL: "/images/01 Painter house with tree 8x10.jpg",
  },
  {
    title: "Paw's house on Nashville - 02",
    description: "Paw's house on Nashville - 02",
    category: "CONTEMPORARY",
    imageURL: "/images/02 Paw_s house on Nashville 8x10.jpg",
  },
  {
    title: "Grace Episcopal Church - 03",
    description: "Grace Episcopal Church - 03",
    category: "CONTEMPORARY",
    imageURL: "/images/03 Grace Episcopal Church 8x10.jpg",
  },
  {
    title: "WOWL - 04",
    description: "WOWL - 04",
    category: "CONTEMPORARY",
    imageURL: "/images/04 WOWL 8x10.jpg",
  },
  {
    title: "Atlanta  Avenue Elementary - 05",
    description: "Atlanta  Avenue Elementary - 05",
    category: "CONTEMPORARY",
    imageURL: "/images/05 Atlanta  Avenue Elementary 8x10.jpg",
  },
  {
    title: "Crumps camera shop - 06",
    description: "Crumps camera shop - 06",
    category: "CONTEMPORARY",
    imageURL: "/images/06 Crumps camera shop 8x10.jpg",
  },
  {
    title: "Habler House - 07",
    description: "Habler House - 07",
    category: "CONTEMPORARY",
    imageURL: "/images/07 Habler House 8x10.jpg",
  },
  {
    title: "Sheffield Standpipe - 08",
    description: "Sheffield Standpipe - 08",
    category: "CONTEMPORARY",
    imageURL: "/images/08 Sheffield Standpipe 8x10.jpg",
  },
  {
    title: "Sears Riverbluff - 09",
    description: "Sears Riverbluff - 09",
    category: "CONTEMPORARY",
    imageURL: "/images/09 Sears Riverbluff 8x10.jpg",
  },
  {
    title: "Sterling - 10",
    description: "Sterling - 10",
    category: "CONTEMPORARY",
    imageURL: "/images/10 Sterling 8x10.jpg",
  },
  {
    title: "Colbert Theater - 11",
    description: "Colbert Theater - 11",
    category: "CONTEMPORARY",
    imageURL: "/images/11 Colbert Theater 8x10.jpg",
  },
  {
    title: "St Joseph Catholic Church - 12",
    description: "St Joseph Catholic Church - 12",
    category: "CONTEMPORARY",
    imageURL: "/images/12 St Joseph Catholic Church 8x10.jpg",
  },
  {
    title: "twin houses - 13",
    description: "twin houses - 13",
    category: "CONTEMPORARY",
    imageURL: "/images/13 twin houses 8x10.jpg",
  },
  {
    title: "Roulhac house - 14",
    description: "Roulhac house - 14",
    category: "CONTEMPORARY",
    imageURL: "/images/14 Roulhac house 8x10.jpg",
  },
  {
    title: "River Oaks - 15",
    description: "River Oaks - 15",
    category: "CONTEMPORARY",
    imageURL: "/images/15 River Oaks 8x10.jpg",
  },
  {
    title: "Dairy Queen - 16",
    description: "Dairy Queen - 16",
    category: "CONTEMPORARY",
    imageURL: "/images/16 Dairy Queen 8x10.jpg",
  },
  {
    title: "Liberty Super Market - 17",
    description: "Liberty Super Market - 17",
    category: "CONTEMPORARY",
    imageURL: "/images/17 Liberty Super Market 8x10.jpg",
  },
  {
    title: "Barner house - 18",
    description: "Barner house - 18",
    category: "CONTEMPORARY",
    imageURL: "/images/18 Barner house 8x10.jpg",
  },
  {
    title: "Spalding House - 19",
    description: "Spalding House - 19",
    category: "CONTEMPORARY",
    imageURL: "/images/19 Spalding House 8x10.jpg",
  },
  {
    title: "Walgreens - 20",
    description: "Walgreens - 20",
    category: "CONTEMPORARY",
    imageURL: "/images/20 Walgreens 8x10.jpg",
  },
  {
    title: "Atlanta Avenue House - 21",
    description: "Atlanta Avenue House - 21",
    category: "CONTEMPORARY",
    imageURL: "/images/21 Atlanta Avenue House 8x10.jpg",
  },
  {
    title: "Mrs Thompson on Montgomery - 22",
    description: "Mrs Thompson on Montgomery - 22",
    category: "CONTEMPORARY",
    imageURL: "/images/22 Mrs Thompson on Montgomery 8x10.jpg",
  },
  {
    title: "Beard House - 23",
    description: "Beard House - 23",
    category: "CONTEMPORARY",
    imageURL: "/images/23 Beard House 8x10.jpg",
  },
  {
    title: "Beards Nehi Bottling Co - 24",
    description: "Beards Nehi Bottling Co - 24",
    category: "CONTEMPORARY",
    imageURL: "/images/24 Beards Nehi Bottling Co 8x10.jpg",
  },
  {
    title: "Belmont Hospital - 25",
    description: "Belmont Hospital - 25",
    category: "CONTEMPORARY",
    imageURL: "/images/25 Belmont Hospital 8x10.jpg",
  },
  {
    title: "first baptist church - 26",
    description: "first baptist church - 26",
    category: "CONTEMPORARY",
    imageURL: "/images/26 first baptist church 8x10.jpg",
  },
  {
    title: "conner's service station - 27",
    description: "conner's service station - 27",
    category: "CONTEMPORARY",
    imageURL: "/images/27 conner_s service station 8x10.jpg",
  },
  {
    title: "lucky minnow farm - 28",
    description: "lucky minnow farm - 28",
    category: "CONTEMPORARY",
    imageURL: "/images/28 lucky minnow farm 8x10.jpg",
  },
  {
    title: "Cohen House 1210 Montgomery - 29",
    description: "Cohen House 1210 Montgomery - 29",
    category: "CONTEMPORARY",
    imageURL: "/images/29 Cohen House 1210 Montgomery 8x10.jpg",
  },
  {
    title: "Lustron House in Village - 30",
    description: "Lustron House in Village - 30",
    category: "CONTEMPORARY",
    imageURL: "/images/30 Lustron House in Village 8x10.jpg",
  },
  {
    title: "Skateland - 31",
    description: "Skateland - 31",
    category: "CONTEMPORARY",
    imageURL: "/images/31 Skateland 8x10.jpg",
  },
  {
    title: "Nine Row redo - 32",
    description: "Nine Row redo - 32",
    category: "CONTEMPORARY",
    imageURL: "/images/32 Nine Row redo 8x10.jpg",
  },
  {
    title: "train depot 01 - 33",
    description: "train depot 01 - 33",
    category: "CONTEMPORARY",
    imageURL: "/images/33 train depot 01 8x10.jpg",
  },
  {
    title: "Yellow Cab - 34",
    description: "Yellow Cab - 34",
    category: "CONTEMPORARY",
    imageURL: "/images/34 Yellow Cab 8x10.jpg",
  },
  {
    title: "train depot 02 - 35",
    description: "train depot 02 - 35",
    category: "CONTEMPORARY",
    imageURL: "/images/35 train depot 02 8x10.jpg",
  },
  {
    title: "Alabama Ave School - 36",
    description: "Alabama Ave School - 36",
    category: "CONTEMPORARY",
    imageURL: "/images/36 Alabama Ave School 8x10.jpg",
  },
  {
    title: "Moses House - 37",
    description: "Moses House - 37",
    category: "CONTEMPORARY",
    imageURL: "/images/37 Moses House 8 x 10.jpg",
  },
  {
    title: "furnace Hill - 38",
    description: "furnace Hill - 38",
    category: "CONTEMPORARY",
    imageURL: "/images/38 furnace Hill 8 x 10.jpg",
  },
  {
    title: "Swoopes - 39",
    description: "Swoopes - 39",
    category: "CONTEMPORARY",
    imageURL: "/images/39 Swoopes 8 x 10.jpg",
  },
  {
    title: "City Hall - 40",
    description: "City Hall - 40",
    category: "CONTEMPORARY",
    imageURL: "/images/40 City Hall 8 x 10.jpg",
  },
  {
    title: "City of Sheffield river boat - 41",
    description: "City of Sheffield river boat - 41",
    category: "CONTEMPORARY",
    imageURL: "/images/41 City of Sheffield river boat 8 x 10.jpg",
  },
  {
    title: "Streit Milk - 42",
    description: "Streit Milk - 42",
    category: "CONTEMPORARY",
    imageURL: "/images/42 Streit Milk 8 x 10.jpg",
  },
  {
    title: "Robert and Debbies twin houses - 43",
    description: "Robert and Debbies twin houses - 43",
    category: "CONTEMPORARY",
    imageURL: "/images/43 Robert and Debbies twin houses 8 x 10.jpg",
  },
  {
    title: "Christy Bldg Galloway - 44",
    description: "Christy Bldg Galloway - 44",
    category: "CONTEMPORARY",
    imageURL: "/images/44 Christy Bldg Galloway 8 x 10.jpg",
  },
  {
    title: "Jewish - 45",
    description: "Jewish - 45",
    category: "CONTEMPORARY",
    imageURL: "/images/45 Jewish 8 x 10.jpg",
  },
  {
    title: "King House - 46",
    description: "King House - 46",
    category: "CONTEMPORARY",
    imageURL: "/images/46 King House 8 x 10.jpg",
  },
  {
    title: "catholic school on dover - 47",
    description: "catholic school on dover - 47",
    category: "CONTEMPORARY",
    imageURL: "/images/47 catholic school on dover 8 x 10.jpg",
  },
  {
    title: "house on Montgomery next to apartments - 48",
    description: "house on Montgomery next to apartments - 48",
    category: "CONTEMPORARY",
    imageURL: "/images/48 house on Montgomery next to apartments 8 x 10.jpg",
  },
  {
    title: "Mother's house Whitten house - 49",
    description: "Mother's house Whitten house - 49",
    category: "CONTEMPORARY",
    imageURL: "/images/49 Mother_s house Whitten house 8 x 10.jpg",
  },
  {
    title: "Columbia Ave Presbyterian church - 50",
    description: "Columbia Ave Presbyterian church - 50",
    category: "CONTEMPORARY",
    imageURL: "/images/50 Columbia Ave Presbyterian church 8 x 10.jpg",
  },
  {
    title: "catholic Presbytry - 51",
    description: "catholic Presbytry - 51",
    category: "CONTEMPORARY",
    imageURL: "/images/51 catholic Presbytry 8 x 10.jpg",
  },
  {
    title: "Odell Willingham market - 52",
    description: "Odell Willingham market - 52",
    category: "CONTEMPORARY",
    imageURL: "/images/52 Odell Willingham market 8 x 10.jpg",
  },
  {
    title: "cape code on Park Blvd - 53",
    description: "cape code on Park Blvd - 53",
    category: "CONTEMPORARY",
    imageURL: "/images/53 cape code on Park Blvd 8 x 10.jpg",
  },
  {
    title: "lagomarsino house - 54",
    description: "lagomarsino house - 54",
    category: "CONTEMPORARY",
    imageURL: "/images/54 lagomarsino house 8 x 10.jpg",
  },
  {
    title: "thurmond house - 55",
    description: "thurmond house - 55",
    category: "CONTEMPORARY",
    imageURL: "/images/55 thurmond house 8 x 10.jpg",
  },
  {
    title: "First Presbyterian windows - 56",
    description: "First Presbyterian windows - 56",
    category: "CONTEMPORARY",
    imageURL: "/images/56 First Presbyterian windows 8x10.jpg",
  },
  {
    title: "1st Presbyterian exterior - 57",
    description: "1st Presbyterian exterior - 57",
    category: "CONTEMPORARY",
    imageURL: "/images/57 1st Presbyterian exterior 8x10.jpg",
  },
  {
    title: "Community Center - 58",
    description: "Community Center - 58",
    category: "CONTEMPORARY",
    imageURL: "/images/58 Community Center 8x10.jpg",
  },
  {
    title: "River Oaks with monkeys - 59",
    description: "River Oaks with monkeys - 59",
    category: "CONTEMPORARY",
    imageURL: "/images/59 River Oaks with monkeys 8x10.jpg",
  },
  {
    title: "Morris House on Nashville - 60",
    description: "Morris House on Nashville - 60",
    category: "CONTEMPORARY",
    imageURL: "/images/60 Morris House on Nashville 8x10.jpg",
  },
  {
    title: "Blair House - 61",
    description: "Blair House - 61",
    category: "CONTEMPORARY",
    imageURL: "/images/61 Blair House 8x10.jpg",
  },
  {
    title: "Crowe House Park Blvd - 62",
    description: "Crowe House Park Blvd - 62",
    category: "CONTEMPORARY",
    imageURL: "/images/62 Crowe House Park Blvd 8x10.jpg",
  },
  {
    title: "gordon Drive 4 square - 63",
    description: "gordon Drive 4 square - 63",
    category: "CONTEMPORARY",
    imageURL: "/images/63 gordon Drive 4 square 8x10.jpg",
  },
  {
    title: "montgomery and 8th 4 square - 64",
    description: "montgomery and 8th 4 square - 64",
    category: "CONTEMPORARY",
    imageURL: "/images/64 montgomery and 8th 4 square 8x10.jpg",
  },
  {
    title: "Keyes House - 65",
    description: "Keyes House - 65",
    category: "CONTEMPORARY",
    imageURL: "/images/65 Keyes House 8x10.jpg",
  },
  {
    title: "Chamber of Conmerce - 66",
    description: "Chamber of Conmerce - 66",
    category: "CONTEMPORARY",
    imageURL: "/images/66 Chamber of Conmerce 8x10.jpg",
  },
  {
    title: "Sheffield High - 67",
    description: "Sheffield High - 67",
    category: "CONTEMPORARY",
    imageURL: "/images/67 Sheffield High 8x10.jpg",
  },
  {
    title: "Sheffield Pharmacy - 68",
    description: "Sheffield Pharmacy - 68",
    category: "CONTEMPORARY",
    imageURL: "/images/68 Sheffield Pharmacy 8x10.jpg",
  },
  {
    title: "Moog Ware Buildings - 69",
    description: "Moog Ware Buildings - 69",
    category: "CONTEMPORARY",
    imageURL: "/images/69 Moog Ware Buildings 8x10.jpg",
  },
  {
    title: "Howard Victorian on Montgomery - 70",
    description: "Howard Victorian on Montgomery - 70",
    category: "CONTEMPORARY",
    imageURL: "/images/70 Howard Victorian on Montgomery 8x10.jpg",
  },
  {
    title: "Wilson Craftsman bungalow on Montgomery - 71",
    description: "Wilson Craftsman bungalow on Montgomery - 71",
    category: "CONTEMPORARY",
    imageURL: "/images/71 Wilson Craftsman bungalow on Montgomery 8x10.jpg",
  },
  {
    title: "Grant Hotel - 72",
    description: "Grant Hotel - 72",
    category: "CONTEMPORARY",
    imageURL: "/images/72 Grant Hotel 8x10.jpg",
  },
  {
    title: "first train depot - 73",
    description: "first train depot - 73",
    category: "CONTEMPORARY",
    imageURL: "/images/73 first train depot 8x10.jpg",
  },
  {
    title: "Pride of Dixie syrup plant - 74",
    description: "Pride of Dixie syrup plant - 74",
    category: "CONTEMPORARY",
    imageURL: "/images/74 Pride of Dixie syrup plant 8x10.jpg",
  },
  {
    title: "craft home on Gordon drive - 75",
    description: "craft home on Gordon drive - 75",
    category: "CONTEMPORARY",
    imageURL: "/images/75 craft home on Gordon drive 8x10.jpg",
  },
  {
    title: "santa - 76",
    description: "santa - 76",
    category: "CONTEMPORARY",
    imageURL: "/images/76 santa 8x10.jpg",
  },
  {
    title: "Annapolis Ave Church of Christ 01 - 77",
    description: "Annapolis Ave Church of Christ 01 - 77",
    category: "CONTEMPORARY",
    imageURL: "/images/77 Annapolis Ave Church of Christ 01 8x10.jpg",
  },
  {
    title: "Annapolis Ave Church of Christ 02 - 78",
    description: "Annapolis Ave Church of Christ 02 - 78",
    category: "CONTEMPORARY",
    imageURL: "/images/78 Annapolis Ave Church of Christ 02 8x10.jpg",
  },
  {
    title: "York Terrace Lustron House - 79",
    description: "York Terrace Lustron House - 79",
    category: "CONTEMPORARY",
    imageURL: "/images/79 York Terrace Lustron House 8x10.jpg",
  },
  {
    title: "purple and gold house - 80",
    description: "purple and gold house - 80",
    category: "CONTEMPORARY",
    imageURL: "/images/80 purple and gold house 8x10.jpg",
  },
  {
    title: "905 Montgomery - 81",
    description: "905 Montgomery - 81",
    category: "CONTEMPORARY",
    imageURL: "/images/81 905 Montgomery 8x10.jpg",
  },
  {
    title: "Maud Lindsay - 82",
    description: "Maud Lindsay - 82",
    category: "CONTEMPORARY",
    imageURL: "/images/82 Maud Lindsay 8x10.jpg",
  },
  {
    title: "8th and Nashville - 83",
    description: "8th and Nashville - 83",
    category: "CONTEMPORARY",
    imageURL: "/images/83 8th and Nashville 8x10.jpg",
  },
  {
    title: "Nathan - 84",
    description: "Nathan - 84",
    category: "CONTEMPORARY",
    imageURL: "/images/84 Nathan 8x10.jpg",
  },
  {
    title: "Kienker Building - 85",
    description: "Kienker Building - 85",
    category: "CONTEMPORARY",
    imageURL: "/images/85 Kienker Building 8x10.jpg",
  },
  {
    title: "Pride's Cleaners - 86",
    description: "Pride's Cleaners - 86",
    category: "CONTEMPORARY",
    imageURL: "/images/86 Pride_s Cleaners.jpg",
  },
  {
    title: "Village 01",
    description: "Village 01",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 01.jpg",
  },
  {
    title: "Village 02",
    description: "Village 02",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 02.jpg",
  },
  {
    title: "Village 03",
    description: "Village 03",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 03.jpg",
  },
  {
    title: "Village 04",
    description: "Village 04",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 04.jpg",
  },
  {
    title: "Village 05",
    description: "Village 05",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 05.jpg",
  },
  {
    title: "Village 06",
    description: "Village 06",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 06.jpg",
  },
  {
    title: "Village 07",
    description: "Village 07",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 07.jpg",
  },
  {
    title: "Village 08",
    description: "Village 08",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 08.jpg",
  },
  {
    title: "Village 09",
    description: "Village 09",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 09.jpg",
  },
  {
    title: "Village 10",
    description: "Village 10",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 10.jpg",
  },
  {
    title: "Village 11",
    description: "Village 11",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 11.jpg",
  },
  {
    title: "Village 12",
    description: "Village 12",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 12.jpg",
  },
  {
    title: "Village 13",
    description: "Village 13",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 13.jpg",
  },
  {
    title: "Village 14",
    description: "Village 14",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 14.jpg",
  },
  {
    title: "Village 15",
    description: "Village 15",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 15.jpg",
  },
  {
    title: "Village 16",
    description: "Village 16",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 16.jpg",
  },
  {
    title: "Village 17",
    description: "Village 17",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 17.jpg",
  },
  {
    title: "Village 18",
    description: "Village 18",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 18.jpg",
  },
  {
    title: "Village 19",
    description: "Village 19",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 19.jpg",
  },
  {
    title: "Village 20",
    description: "Village 20",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 20.jpg",
  },
  {
    title: "Village 21",
    description: "Village 21",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 21.jpg",
  },
  {
    title: "Village 22",
    description: "Village 22",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 22.jpg",
  },
  {
    title: "Village 23",
    description: "Village 23",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 23.jpg",
  },
  {
    title: "Village 24",
    description: "Village 24",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 24.jpg",
  },
  {
    title: "Village 25",
    description: "Village 25",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 25.jpg",
  },
  {
    title: "Village 26",
    description: "Village 26",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 26.jpg",
  },
  {
    title: "Village 27",
    description: "Village 27",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 27.jpg",
  },
  {
    title: "Village 28",
    description: "Village 28",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 28.jpg",
  },
  {
    title: "Village 29",
    description: "Village 29",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 29.jpg",
  },
  {
    title: "Village 30",
    description: "Village 30",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 30.jpg",
  },
  {
    title: "Village 31",
    description: "Village 31",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 31.jpg",
  },
  {
    title: "Village 32",
    description: "Village 32",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 32.jpg",
  },
  {
    title: "Village 33",
    description: "Village 33",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 33.jpg",
  },
  {
    title: "Village 34",
    description: "Village 34",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 34.jpg",
  },
  {
    title: "Village 35",
    description: "Village 35",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 35.jpg",
  },
  {
    title: "Village 36",
    description: "Village 36",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 36.jpg",
  },
  {
    title: "Village 37",
    description: "Village 37",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 37.jpg",
  },
  {
    title: "Village 38",
    description: "Village 38",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 38.jpg",
  },
  {
    title: "Village 39",
    description: "Village 39",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 39.jpg",
  },
  {
    title: "Village 40",
    description: "Village 40",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 40.jpg",
  },
  {
    title: "Village 41",
    description: "Village 41",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 41.jpg",
  },
  {
    title: "Village 42",
    description: "Village 42",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 42.jpg",
  },
  {
    title: "Village 43",
    description: "Village 43",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 43.jpg",
  },
  {
    title: "Village 44",
    description: "Village 44",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 44.jpg",
  },
  {
    title: "Village 45",
    description: "Village 45",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 45.jpg",
  },
  {
    title: "Village 46",
    description: "Village 46",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 46.jpg",
  },
  {
    title: "Village 47",
    description: "Village 47",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 47.jpg",
  },
  {
    title: "Village 48",
    description: "Village 48",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 48.jpg",
  },
  {
    title: "Village 49",
    description: "Village 49",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 49.jpg",
  },
  {
    title: "Village 50",
    description: "Village 50",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 50.jpg",
  },
  {
    title: "Village 51",
    description: "Village 51",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 51.jpg",
  },
  {
    title: "Village 52",
    description: "Village 52",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 52.jpg",
  },
  {
    title: "Village 53",
    description: "Village 53",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 53.jpg",
  },
  {
    title: "Village 54",
    description: "Village 54",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 54.jpg",
  },
  {
    title: "Village 55",
    description: "Village 55",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 55.jpg",
  },
  {
    title: "Village 56",
    description: "Village 56",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 56.jpg",
  },
  {
    title: "Village 57",
    description: "Village 57",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 57.jpg",
  },
  {
    title: "Village 58",
    description: "Village 58",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 58.jpg",
  },
  {
    title: "Village 59",
    description: "Village 59",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 59.jpg",
  },
  {
    title: "Village 60",
    description: "Village 60",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 60.jpg",
  },
  {
    title: "Village 61",
    description: "Village 61",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 61.jpg",
  },
  {
    title: "Village 62",
    description: "Village 62",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 62.jpg",
  },
  {
    title: "Village 63",
    description: "Village 63",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 63.jpg",
  },
  {
    title: "Village 64",
    description: "Village 64",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 64.jpg",
  },
  {
    title: "Village 65",
    description: "Village 65",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 65.jpg",
  },
  {
    title: "Village 66",
    description: "Village 66",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 66.jpg",
  },
  {
    title: "Village 67",
    description: "Village 67",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 67.jpg",
  },
  {
    title: "Village 68",
    description: "Village 68",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 68.jpg",
  },
  {
    title: "Village 69",
    description: "Village 69",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 69.jpg",
  },
  {
    title: "Village 70",
    description: "Village 70",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 70.jpg",
  },
  {
    title: "Village 71",
    description: "Village 71",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 71.jpg",
  },
  {
    title: "Village 72",
    description: "Village 72",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 72.jpg",
  },
  {
    title: "Village 73",
    description: "Village 73",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 73.jpg",
  },
  {
    title: "Village 74",
    description: "Village 74",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 74.jpg",
  },
  {
    title: "Village 75",
    description: "Village 75",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 75.jpg",
  },
  {
    title: "Village 76",
    description: "Village 76",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 76.jpg",
  },
  {
    title: "Village 77",
    description: "Village 77",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 77.jpg",
  },
  {
    title: "Village 78",
    description: "Village 78",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 78.jpg",
  },
  {
    title: "Village 79",
    description: "Village 79",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 79.jpg",
  },
  {
    title: "Village 80",
    description: "Village 80",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 80.jpg",
  },
  {
    title: "Village 81",
    description: "Village 81",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 81.jpg",
  },
  {
    title: "Village 82",
    description: "Village 82",
    category: "VILLAGE",
    imageURL: "/images/Village 8x10 82.jpg",
  },
];

async function main() {
  // Seed pricing options
  for (const pricing of pricingOptions) {
    await prisma.pricing.upsert({
      where: { description: pricing.description },
      update: {},
      create: pricing,
    });
  }

  // Seed products
  for (const product of products) {
    await prisma.product.upsert({
      where: { title: product.title },
      update: {},
      create: product,
    });
  }
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
